version: '3'
services:
  mysql:
    image: mysql:8.0.25
    container_name: relayer-mysql
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --sql_mode="" --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: 'test'
      MYSQL_DATABASE: 'test'
      MYSQL_USER: 'test'
      MYSQL_PASSWORD: 'test'
      LANG: C.UTF-8
    volumes:
      - '.mysql:/var/lib/mysql'
    ports:
      - 3337:3306
