app:
  name: APP_NAME
  port: APP_PORT
  env: NODE_ENV

database:
  host: MYSQL_HOST
  port: MYSQL_PORT
  username: MYSQL_USERNAME
  password: MYSQL_PASSWORD
  database: MYSQL_DATABASE

cron:
  enable:
    __name: CRON_ENABLE
    __format: json

rpc: RPC
privateKey: PRIVATE_KEY
relayContract: RELAY_CONTRACT
signerAddress: SIGNER_ADDRESS
threshold: THRESHOLD
maxAmountTx: MAX_AMOUNT_TX
prefixMessage: PREFIX_MESSAGE